spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

telegram:
  name: libs_bot
  key:
